#!/bin/bash

cd "$(dirname "$0")"

mklink () {
	ln -sfv "$2" "$1"
}

mklink configs/shavit-advertisements.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-advertisements.cfg"
mklink configs/shavit-chat.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-chat.cfg"
mklink configs/shavit-chatsettings.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-chatsettings.cfg"
mklink configs/shavit-mapfixes.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-mapfixes.cfg"
mklink configs/shavit-messages.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-messages.cfg"
mklink configs/shavit-prefix.txt "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-prefix.txt"
mklink configs/shavit-replay.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-replay.cfg"
mklink configs/shavit-sounds.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-sounds.cfg"
mklink configs/shavit-styles.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-styles.cfg"
mklink configs/shavit-zones.cfg "$HOME/code/bhoptimer/addons/sourcemod/configs/shavit-zones.cfg"

mklink scripting/include/convar_class.inc "$HOME/code/bhoptimer/addons/sourcemod/scripting/include/convar_class.inc"
mklink scripting/include/closestpos.inc "$HOME/code/bhoptimer/addons/sourcemod/scripting/include/closestpos.inc"
mklink scripting/include/DynamicChannels.inc "$HOME/code/bhoptimer/addons/sourcemod/scripting/include/DynamicChannels.inc"
mklink scripting/include/rtler.inc "$HOME/code/bhoptimer/addons/sourcemod/scripting/include/rtler.inc"
mklink scripting/include/SteamWorks.inc "$HOME/code/bhoptimer/addons/sourcemod/scripting/include/SteamWorks.inc"

mklink gamedata/shavit.games.txt "$HOME/code/bhoptimer/addons/sourcemod/gamedata/shavit.games.txt"
mklink scripting/include/shavit.inc "$HOME/code/bhoptimer/addons/sourcemod/scripting/include/shavit.inc"
mklink scripting/include/shavit "$HOME/code/bhoptimer/addons/sourcemod/scripting/include/shavit"
mklink scripting/include/srcwr "$HOME/code/bhoptimer/addons/sourcemod/scripting/include/srcwr"
mklink scripting/shavit-chat.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-chat.sp"
mklink scripting/shavit-checkpoints.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-checkpoints.sp"
mklink scripting/shavit-core.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-core.sp"
mklink scripting/shavit-hud.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-hud.sp"
mklink scripting/shavit-mapchooser.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-mapchooser.sp"
mklink scripting/shavit-misc.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-misc.sp"
mklink scripting/shavit-rankings.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-rankings.sp"
#mklink scripting/shavit-replay.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-replay.sp"
mklink scripting/shavit-replay-playback.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-replay-playback.sp"
mklink scripting/shavit-replay-recorder.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-replay-recorder.sp"
mklink scripting/shavit-sounds.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-sounds.sp"
mklink scripting/shavit-stats.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-stats.sp"
mklink scripting/shavit-tas.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-tas.sp"
mklink scripting/shavit-timelimit.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-timelimit.sp"
mklink scripting/shavit-wr.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-wr.sp"
mklink scripting/shavit-zones.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-zones.sp"
mklink scripting/shavit-zones-json.sp "$HOME/code/bhoptimer/addons/sourcemod/scripting/shavit-zones-json.sp"

mklink translations/shavit-chat.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-chat.phrases.txt"
mklink translations/shavit-common.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-common.phrases.txt"
mklink translations/shavit-core.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-core.phrases.txt"
mklink translations/shavit-hud.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-hud.phrases.txt"
mklink translations/shavit-misc.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-misc.phrases.txt"
mklink translations/shavit-rankings.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-rankings.phrases.txt"
mklink translations/shavit-replay.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-replay.phrases.txt"
mklink translations/shavit-stats.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-stats.phrases.txt"
mklink translations/shavit-wr.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-wr.phrases.txt"
mklink translations/shavit-zones.phrases.txt "$HOME/code/bhoptimer/addons/sourcemod/translations/shavit-zones.phrases.txt"

mklink gamedata/eventfix.games.txt "$HOME/code/eventqueue-fix/gamedata/eventfix.games.txt"
mklink scripting/include/eventqueuefix.inc "$HOME/code/eventqueue-fix/scripting/include/eventqueuefix.inc"
mklink scripting/eventqueuefix.sp "$HOME/code/eventqueue-fix/scripting/eventqueuefix.sp"

mklink scripting/mpbhops_but_working.sp "$HOME/code/mpbhops_but_working/addons/sourcemod/scripting/mpbhops_but_working.sp"

#mklink "../../maps" "$HOME/css_maps"
